### PR TITLE
Add AUR download link for Arch-based distros

### PR DESCRIPTION
**Pull request by SergeyKasmy**

### CODE REVIEW

**Comment by althonos** [comment]
If I'm not mistaken, you should add all dependencies to the `depends` key in the PKGBUILD, so you should probably add [`python-sh`](https://www.archlinux.org/packages/community/any/python-sh/) and [`python-tqdm`](https://www.archlinux.org/packages/community/any/python-tqdm/).

Thanks for the AUR package!

**Comment by SergeyKasmy** [comment]
Yeah, you're completely right. I knew I'd forgotten something!

**Comment by SergeyKasmy** [comment]
Done. Everything should work fine now

**Comment by althonos** [comment]
Thanks !

**Pull request merged**
